### ISSUE TITLE
Summer of Code

### ISSUE THREAD

**Issue by bashrc** [barbalet/nobleape#13]
It's too late for this year, but should Noble Ape try entering into the Google Summer of Code?  Perhaps there would be too much work involved in supervising students.

**Comment by meric** [comment]
@barbalet @bashrc It's December, getting close to February 2016.

**Comment by bashrc** [comment]
I'm note sure what the schedule is for SoC

**Comment by bashrc** [comment]
https://developers.google.com/open-source/gsoc/timeline

**Comment by barbalet** [comment]
Here are some of my ideas, open for comment:

https://docs.google.com/document/d/1qnWNDG6x9gU3RgR-7W2INaGWRJEVPWal7sPnRd5sUe8/edit?usp=sharing

**Comment by barbalet** [comment]
http://www.nobleape.com/gorilla.html
