### ISSUE TITLE
not building on linux

### ISSUE THREAD

**Issue by aaannndddyyy** [barbalet/nobleape#46]
According to the documentation, linux_gui.sh builds the gui version, yet this file is absent. 
The only remaining bash script is linux.sh, which appartently does nothing:

nick@host:~/Downloads/nobleape-b42ec665d37751009459e1731ae56fa919325ae3/sim$ ./linux.sh 
nick@host:~/Downloads/nobleape-b42ec665d37751009459e1731ae56fa919325ae3/sim$ 

System: trisquel gnu/linux.

and I have build-essential libtool autotools-dev automake checkinstall check installed

**Comment by barbalet** [comment]
lgml-tbarbalet:~ tbarbalet$ cd github
lgml-tbarbalet:github tbarbalet$ cd nobleape
lgml-tbarbalet:nobleape tbarbalet$ cd sim
lgml-tbarbalet:sim tbarbalet$ ./linux.sh
lgml-tbarbalet:sim tbarbalet$ ls
doc.sh		gui		longterm.c	noble		universe
documentation	ios		mac		test		win
entity		linux.sh	macsim		topdown
lgml-tbarbalet:sim tbarbalet$ cd ..
lgml-tbarbalet:nobleape tbarbalet$ cd ..
lgml-tbarbalet:github tbarbalet$ ls
Debug		complexenv	nalongterm	war
Release		mushroom	nobleape
lgml-tbarbalet:github tbarbalet$ 

It builds nalongterm two directories up (i.e. outside the git repository). That is executable with a help facility as well.

**Comment by aaannndddyyy** [comment]
oh, I always only looked inside the nobleape dir. It used to store it in there before. now it saved it to ~/Downloads. But still, no gui version for linux??

**Comment by bashrc** [comment]
There was a Qt gui, but I think it got deprecated. Qt5 would be an obvious choice for a new gui, because you can do all sorts of fancy transitions.

**Comment by aaannndddyyy** [comment]
I'd be happy if gui were coming back to linux. I'll keep an eye on it. Thx

**Comment by barbalet** [comment]
As with the Windows version there probably needs to be someone maintaining each platform version. The problem with Qt was Mac support was dropped so I couldn't maintain the Qt version of Noble Ape easily. I'm more than happy to maintain versions I develop with periodically.
