### ISSUE TITLE
NobleApeServer.js

### ISSUE THREAD

**Issue by bashrc** [barbalet/nobleape#50]
Is that really javascript?

**Comment by barbalet** [comment]
Per:

https://github.com/barbalet/nobleape/commit/a86895b3935aa80b17d199d479cf0aabf2edc39e#diff-93f725a07423fe1c889f448b33d21f46

The aim is to start with existing C files to provide the structure. Initially rewrite the functionality in Java with unit tests and then produce a JS version of the Java implementation. There are currently placeholder .js files as I originally anticipated rewriting in JS. I can remove the bogus .js files if you think they are confusing.

**Comment by barbalet** [comment]
https://github.com/barbalet/nobleape/commit/178713feb41b004de48bc6a4022a599f4f992110
